apiVersion: v2
name: wafie
description: WAFie Control Plane - Kubernetes native WAF and API Security Protection
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: postgresql
    version: 18.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
