apiVersion: v2
name: wafie
description: WAFie Control Plane - Kubernetes native WAF and API Security Protection
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: postgresql
    version: 16.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
