apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wafie-control-plane
  namespace: {{.Release.Namespace}}
spec:
  rules:
    - host: "wafie-control-plane-{{ .Values.baseHost }}"
      http:
        paths:
          - backend:
              service:
                name: wafie-control-plane
                port:
                  name: api-server
            path: /
            pathType: ImplementationSpecific