apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.controlPlane.svc.name }}
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: wafie-control-plane
  ports:
    - name: api-server
      port: 80
      targetPort: api-server
    - name: gwctrl-server
      port: 18000
      targetPort: gwctrl-server
    - name: waf-gateway
      port: 8888
      targetPort: waf-gateway