apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tm
  namespace: {{.Release.Namespace}}
spec:
  rules:
    - host: "wtm.{{ .Values.baseHost }}"
      http:
        paths:
          - backend:
              service:
                name: wafie-traffic-mirror
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific