apiVersion: v1
kind: Service
metadata:
  name: wafie-traffic-mirror
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: wafie-traffic-mirror
  ports:
    - name: http
      port: 80
      targetPort: http